FROM python:3.11-slim

RUN apt-get update && apt-get install -y --no-install-recommends \
    libglib2.0-0 libsm6 libxrender1 libxext6 \
    && apt-get clean && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY app/ /app/
COPY model/ /app/model/
COPY app/requirements.txt example.jpg .

RUN pip install --no-cache-dir -r requirements.txt

ENTRYPOINT ["python", "inference.py", "example.jpg"]
